### ISSUE TITLE
Update Score gif with latest from sample-app-gif

### ISSUE THREAD

**Issue by astromechza** [score-spec/score.dev#6]
The gif <https://github.com/score-spec/sample-app-gif> has been updated with a higher resolution, and updated theme colors and can be updated in the website. It should also be made slightly larger scale so that the font is more legible.

**Comment by sujaya-sys** [comment]
@FL303 I was wondering if this is something you could look into (possibly with support of the person that helped us to migrate to hugo?) It'll be great to:

* Update the gif as mentioned above
* Increase the size as mentioned above
* Position it so that its no longer covered by the graphic - atm its not possible to read what it says at the bottom

<img width="763" alt="Screenshot 2024-08-03 at 08 59 54" src="https://github.com/user-attachments/assets/ede8875f-ee90-4dab-9caa-7db069ae3008">

Thanks for checking!!

**Comment by FL303** [comment]
@sberoch, could you please double-check to see if we are using this version now?
https://github.com/score-spec/sample-app-gif

**Comment by mathieu-benoit** [comment]
@FL303 @sujaya-sys, can we close this issue now https://github.com/score-spec/score.dev/pull/13 is merged?

**Comment by FL303** [comment]
Yes, can be closed.
